resources:
- name: minimal-vm
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: zones/us-central1-a/machineTypes/g1-small
    tags:
      items:
      - http-server
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          apt-get update
          apt-get install -y apache2 php
          echo "<?php echo '<h1>Hello World</h1><p></p>'; ?>" > /var/www/html/index.php
          systemctl restart apache2
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: projects/debian-cloud/global/images/family/debian-11
    networkInterfaces:
    - network: global/networks/default
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT

- name: allow-http
  type: compute.v1.firewall
  properties:
    network: global/networks/default
    allowed:
    - IPProtocol: TCP
      ports:
      - "80"
    sourceRanges:
    - "0.0.0.0/0"
    targetTags:
    - http-server